spring:
  application:
    name: grocery-store
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: 0
  datasource:
    # Ensure the SQL Server driver sends string parameters as Unicode
    url: jdbc:sqlserver://SQL50XX.site4now.net:1433;databaseName=grocerystore;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
    username: db_ace0d7_grocerystore_admin
    password: Smarter2026#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # Force HTTP/JSON encoding to UTF-8 to preserve Myanmar characters in responses
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

app:
  admin:
    username: admin
    password: htoo123!@#
  uploads:
    payment-dir: uploads/payments
  payment:
    kpay-phone: "09 96 2800 540"
    wave-phone: "09 96 2800 540"

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dzq4fv63}
  api-key: ${CLOUDINARY_API_KEY:362331865784937}
  api-secret: ${CLOUDINARY_API_SECRET:bSE0KQTaXpNirJ9Ef-FptCtgucs}
